// Generated by setup.html on 2026-09-28T23:55:19.984Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://niacgwpunsfefftjfdyn.supabase.co";
window.SUPABASE_KEY = "sb_publishable_TrY-_7JrQ-CORhRrQkOgfg_nbvts8e5";
